# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.1/variables.json
Variables:
  AI:
    # [enum: OpenAI, AzureOpenAI, Gemini]
    DefaultProvider: ""
    # If set to true, built-in guardrails will be applied.
    UseGuardrails: true