# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/rest-clients.json
RestClients:
  mockClient:
    UUID: 6d2ae39a-e851-4da2-b03b-bc6e1bcfaf85
    Url: '{ivy.app.baseurl}/api/aiMock'
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
