# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.1/variables.json
Variables:
  AI:
    Providers:
      AzureOpenAI:
        # The endpoint of your Azure OpenAI resource, e.g., "https://my-openai-resource.openai.azure.com/"
        Endpoint: https://my-openai-resource.openai.azure.com/
        # The deployment name to use by default.
        DefaultDeployment: your-deployment-name
        # Model deployments configured in your Azure OpenAI resource.
        # Each deployment is a variable consist of 'Model' and 'APIKey' fields.
        # Because each deployment is a YAML variable, they should follow these naming rules:
        # - Use lowercase letters, numbers, and hyphens (kebab-case).
        # - Avoid spaces, special characters, and starting with digits.
        # For example: 'Deployment_1', 'test-gpt-4-1-mini'
        Deployments:
          your-deployment-name:
            Model: gpt-4.1-mini
            #[password]
            APIKey: ${decrypt:1234}
          another-deployment-name:
            Model: gpt-4o
            #[password]
            APIKey: ${decrypt:abcd}