# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.1/variables.json
Variables:
  AI:
    Providers:
      Gemini:
        #[password]
        APIKey: ${decrypt:}
        BaseUrl: ""
        # The default model, if not explicitly specified on the calling Agent.
        #
        # [enum: gemini-2.5-pro, gemini-2.5-flash, gemini-2.0-flash-exp, gemini-2.0-flash, gemini-1.5-flash, gemini-1.5-pro]
        DefaultModel: ""
