# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/variables.json
Variables:
  AiDemo:
    # [file: json]
    Employee: ""
    # [file: json]
    Department: ""
    # [file: json]
    SupportTicket: ""
